# Generated by Django 2.0.2 on 2018-03-06 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20180306_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.FileField(upload_to='news', verbose_name='Картинка'),
        ),
    ]
