# Generated by Django 2.0.2 on 2018-03-06 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20180306_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.FileField(upload_to='news_files', verbose_name='Картинка'),
        ),
    ]
