# Generated by Django 2.0.2 on 2018-03-15 18:24

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20180306_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='text',
            field=tinymce.models.HTMLField(verbose_name='Текст'),
        ),
    ]
