# Generated by Django 2.0.1 on 2018-01-15 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('year', models.DateTimeField()),
                ('image', models.ImageField(upload_to='')),
                ('gears', models.PositiveIntegerField(choices=[(0, 'Автомат'), (1, 'Механическая')], default=0)),
                ('engine', models.DecimalField(decimal_places=2, max_digits=2)),
                ('min_age', models.PositiveIntegerField(default=18)),
                ('experience', models.PositiveIntegerField(default=3)),
            ],
        ),
    ]
