# Generated by Django 2.0.1 on 2018-01-15 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_car', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='year',
            field=models.DateField(),
        ),
    ]
