# Generated by Django 2.0.1 on 2018-01-15 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_car', '0003_auto_20180115_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='year',
            field=models.CharField(default='2018', max_length=4),
        ),
    ]
