# Generated by Django 2.0.1 on 2018-01-15 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_car', '0004_auto_20180115_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='engine',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
