# Generated by Django 2.0.1 on 2018-01-15 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_car', '0005_auto_20180115_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='price',
            field=models.PositiveIntegerField(default=1300, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='auto',
            name='engine',
            field=models.DecimalField(decimal_places=1, max_digits=2, verbose_name='Двигатель'),
        ),
        migrations.AlterField(
            model_name='auto',
            name='experience',
            field=models.PositiveIntegerField(default=3, verbose_name='Опыт вожжения'),
        ),
        migrations.AlterField(
            model_name='auto',
            name='gears',
            field=models.PositiveIntegerField(choices=[(0, 'Автомат'), (1, 'Механическая')], default=0, verbose_name='Коробка'),
        ),
        migrations.AlterField(
            model_name='auto',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='auto',
            name='min_age',
            field=models.PositiveIntegerField(default=18, verbose_name='Минимальный возраст'),
        ),
        migrations.AlterField(
            model_name='auto',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='auto',
            name='year',
            field=models.CharField(default='2018', max_length=4, verbose_name='Год выпуска'),
        ),
    ]
