# Generated by Django 2.0.1 on 2018-01-15 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_car', '0006_auto_20180115_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='experience',
            field=models.PositiveIntegerField(default=3, verbose_name='Опыт вождения'),
        ),
        migrations.AlterField(
            model_name='auto',
            name='image',
            field=models.ImageField(upload_to='rent_car/static/img', verbose_name='Изображение'),
        ),
    ]
