# Generated by Django 2.0.1 on 2018-01-15 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_car', '0007_auto_20180115_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='image',
            field=models.FileField(blank=True, upload_to='', verbose_name='Изображение'),
        ),
    ]
