# Generated by Django 2.0.1 on 2018-01-16 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rent_car', '0008_auto_20180115_1920'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Название')),
            ],
        ),
        migrations.AlterModelOptions(
            name='auto',
            options={'verbose_name_plural': 'Авто'},
        ),
        migrations.AddField(
            model_name='auto',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='rent_car.Category'),
        ),
    ]
