# Generated by Django 2.0.1 on 2018-01-16 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rent_car', '0009_auto_20180116_0827'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarkAuto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Марка')),
            ],
            options={
                'verbose_name_plural': 'Марки авто',
            },
        ),
        migrations.CreateModel(
            name='ModelAuto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('mark', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rent_car.MarkAuto', verbose_name='Марка авто')),
            ],
            options={
                'verbose_name_plural': 'Модели авто',
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Категории авто'},
        ),
        migrations.RemoveField(
            model_name='auto',
            name='category',
        ),
        migrations.AddField(
            model_name='auto',
            name='category',
            field=models.ManyToManyField(default=0, to='rent_car.Category', verbose_name='Категория'),
        ),
    ]
