# Generated by Django 2.0.1 on 2018-01-16 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rent_car', '0010_auto_20180116_0852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auto',
            name='name',
        ),
        migrations.AddField(
            model_name='auto',
            name='mark',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='rent_car.MarkAuto', verbose_name='Марка'),
        ),
        migrations.AddField(
            model_name='auto',
            name='model',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='rent_car.ModelAuto', verbose_name='Модель'),
        ),
    ]
