# Generated by Django 2.0.1 on 2018-01-16 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent_car', '0011_auto_20180116_0857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auto',
            name='model',
        ),
    ]
