# Generated by Django 2.0.1 on 2018-01-16 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rent_car', '0012_remove_auto_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='model',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='rent_car.ModelAuto', verbose_name='Модель'),
        ),
    ]
