# Generated by Django 2.0.1 on 2018-01-17 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rent_car', '0013_auto_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='engine',
            field=models.DecimalField(decimal_places=1, default=1.6, max_digits=2, verbose_name='Двигатель'),
        ),
        migrations.AlterField(
            model_name='auto',
            name='image',
            field=models.FileField(blank=True, upload_to='auto', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='modelauto',
            name='mark',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rent_car.MarkAuto', verbose_name='Марка авто'),
        ),
    ]
