# Generated by Django 2.0.1 on 2018-01-20 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent_car', '0014_auto_20180117_1810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auto',
            name='mark',
        ),
    ]
