# Generated by Django 2.0.2 on 2018-02-27 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rent_car', '0015_remove_auto_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelauto',
            name='mark',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rent_car.MarkAuto', verbose_name='Марка авто'),
        ),
    ]
