# Generated by Django 2.0.2 on 2018-03-02 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_car', '0021_auto_20180227_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='description',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
    ]
