# Generated by Django 2.0.2 on 2018-03-05 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rent_car', '0023_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='auto')),
            ],
            options={
                'verbose_name_plural': 'Фотографии',
                'verbose_name': 'Фотографии',
            },
        ),
        migrations.RemoveField(
            model_name='modelauto',
            name='mark',
        ),
        migrations.RemoveField(
            model_name='auto',
            name='model',
        ),
        migrations.AlterField(
            model_name='markauto',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Марка'),
        ),
        migrations.AlterField(
            model_name='order',
            name='deadline',
            field=models.CharField(max_length=30, verbose_name='Срок аренды'),
        ),
        migrations.DeleteModel(
            name='ModelAuto',
        ),
        migrations.AddField(
            model_name='autoimage',
            name='auto',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='rent_car.Auto'),
        ),
    ]
