# Generated by Django 2.0.2 on 2018-03-06 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent_car', '0024_auto_20180305_1903'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
