# Generated by Django 2.0.2 on 2018-03-12 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribers',
            name='email',
            field=models.CharField(max_length=50),
        ),
    ]
