# Generated by Django 2.0.2 on 2018-03-13 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0003_auto_20180313_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribers',
            name='email',
            field=models.CharField(max_length=30),
        ),
    ]
