# Generated by Django 2.0.2 on 2018-03-06 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car', models.CharField(max_length=100, verbose_name='Автомобиль')),
                ('name', models.CharField(max_length=30, verbose_name='Имя')),
                ('phone', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('deadline', models.CharField(max_length=30, verbose_name='Срок аренды')),
            ],
            options={
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
